version: '3.7'

services:
  springboot-backend:
    build:
      context: springboot-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  angular-frontend:
    build:
      context: angular-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - springboot-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
