version: '3.8'
services:
  backend:
    build: ./springboot-backend
    container_name: backend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  frontend:
    build: ./angular-frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
